CREATE OR REPLACE
PACKAGE aritmetica IS
  version NUMBER := 1.0;

  PROCEDURE mostrar_info;
  FUNCTION suma       (a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION resta      (a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION multiplica (a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION divide     (a NUMBER, b NUMBER) RETURN NUMBER;
END aritmetica;


CREATE OR REPLACE
PACKAGE BODY aritmetica IS

  PROCEDURE mostrar_info IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE
      ('Paquete de operaciones aritméticas. Versión ' || version);
  END mostrar_info;

  FUNCTION suma       (a NUMBER, b NUMBER) RETURN NUMBER IS
  BEGIN
    RETURN (a+b);
  END suma;

  FUNCTION resta      (a NUMBER, b NUMBER) RETURN NUMBER IS
  BEGIN
    RETURN (a-b);
  END resta;

  FUNCTION multiplica (a NUMBER, b NUMBER) RETURN NUMBER IS
  BEGIN
    RETURN (a*b);
  END multiplica;

  FUNCTION divide     (a NUMBER, b NUMBER) RETURN NUMBER IS
  BEGIN
    RETURN (a/b);
  END divide;

END aritmetica;

-- EJERCICIO  1:
SELECT ARITMETICA.SUMA(4,3) FROM DUAL;
SELECT ARITMETICA.RESTA(4,3) FROM DUAL;
SELECT ARITMETICA.DIVIDE(12,3) FROM DUAL;
SELECT ARITMETICA.MULTIPLICA(4,3) FROM DUAL;

--EJERCICIO 2:
SELECT ARITMETICA.RESTO(7,3) FROM DUAL;

--EJERCICIO 3:
BEGIN
	DBMS_OUTPUT.PUT_LINE('Hola mundo');
END;

BEGIN
	ARITMETICA.INFORMACION();
END;

CREATE TABLE DEP (
NUMDEPT NUMBER(3),
NOMBRE VARCHAR2(25),
PRESUPUESTO NUMBER(5),
PRIMARY KEY (NUMDEPT)
);


--EJERCICIO 4
CREATE SEQUENCE sec_AUMENTO
start with 1
  increment by 1
  maxvalue 99999
  minvalue 1;
-- PACKAGE_GESTION.SQL
CREATE OR REPLACE PACKAGE PAQUETES.GESTION AS
PROCEDURE CREAR_DEP (nombre VARCHAR2, presupuesto NUMBER);
FUNCTION NUM_DEP (nombre VARCHAR2) RETURN NUMBER;
PROCEDURE MOSTRAR_DEP (numero NUMBER);
PROCEDURE BORRAR_DEP (numero NUMBER);
PROCEDURE MODIFICAR_DEP (numero NUMBER, presupuesto NUMBER);
END GESTION;

CREATE OR REPLACE PACKAGE BODY PAQUETES.GESTION IS

  PROCEDURE CREAR_DEP (NOMBRE2 VARCHAR2, PRESUPUESTO2 NUMBER) AS
  BEGIN
	  INSERT INTO DEP (NUMDEPT,NOMBRE,PRESUPUESTO) VALUES (SEC_AUMENTO.NEXTVAL,NOMBRE2,PRESUPUESTO2);
	END CREAR_DEP;
	
	FUNCTION NUM_DEP (NOMBRE2 VARCHAR2) RETURN NUMBER
	IS
		RESULTADO NUMBER;
		CURSOR C IS SELECT NUMDEPT FROM DEP WHERE NOMBRE=NOMBRE2;
	BEGIN
		FOR registro IN C 
		LOOP
				RESULTADO:=registro.NUMDEPT;
		END LOOP;
	
		END NUM_DEP;
	
	PROCEDURE MOSTRAR_DEP (NUMERITO NUMBER)AS
		registro DEP%ROWTYPE;

	BEGIN
	SELECT * INTO registro FROM DEP  WHERE NUMDEPT=NUMERITO;
		
			DBMS_OUTPUT.PUT_LINE('Numero: ' || registro.NUMDEPT || chr(13) ||
								'Nombre: ' || registro.NOMBRE || chr(13) ||
								'Presupuesto' || registro.PRESUPUESTO || chr(13));
		END MOSTRAR_DEP;
	
	PROCEDURE BORRAR_DEP (NUMERO NUMBER) AS
		CURSOR C IS SELECT NUMDEPT FROM DEP WHERE NUMDEPT=NUMERO;

		BEGIN
			FOR registro IN C 
			LOOP
				DELETE FROM DEP WHERE registro.NUMDEPT = NUMERO;

			END LOOP;
	
		END BORRAR_DEP;
	
	PROCEDURE MODIFICAR_DEP(NUMERO NUMBER, PRESUPUESTO2 NUMBER) AS

	BEGIN
				UPDATE DEP
		 		SET NUMDEPT =NUMERO, PRESUPUESTO = PRESUPUESTO2
		 		WHERE NUMDEPT = NUMERO;

	

		END MODIFICAR_DEP;

END GESTION;

SELECT * FROM DEP;

BEGIN
	PAQUETES.GESTION.CREAR_DEPT('FARMACIA',2567);
END;

SELECT * FROM DEP;

SELECT GESTION.NUM_DEPT('FARMACIA') FROM DUAL;

BEGIN
	GESTION.MOSTRAR_DEPT(1);
END;

BEGIN
	GESTION.MODIFICAR_DEPT(21,7777);
END;
SELECT * FROM DEP;

BEGIN
	GESTION.BORRAR_DEP(1);
END;
SELECT * FROM DEP;








