/*ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER JAVIERVH IDENTIFIED BY JAVIERVH;
GRANT CONNECT, RESOURCE, DBA TO JAVIERVH;*/

CREATE TABLE CLIENTES 
(dni VARCHAR2(9),
nombre VARCHAR2(25),
apellidos VARCHAR2(50),
cuidad VARCHAR2(20),

CONSTRAINT PK_CLIENTES PRIMARY KEY (dni)
);

CREATE TABLE MARCAS
(codmarca number(5),
nombre VARCHAR2(25),
pais VARCHAR2(20),

CONSTRAINT PK_MARCAS PRIMARY KEY (codmarca)
);

CREATE TABLE COCHES
(codcoche NUMBER(5),
codmarca NUMBER(5),
modelo VARCHAR2(20),
matricula VARCHAR2(8),
color VARCHAR2(15),

CONSTRAINT PK_COCHES PRIMARY KEY (codcoche),
CONSTRAINT FK_COCHES FOREIGN KEY (codmarca) REFERENCES MARCAS(codmarca)
);

CREATE TABLE CONCESIONARIOS
(cifc VARCHAR2(10),
nombre VARCHAR2(25),
cuidad VARCHAR2(20),
cifcmatriz VARCHAR2(10),

CONSTRAINT PK_CONCESIONARIO PRIMARY KEY (cifc),
CONSTRAINT FK_CONCESIONARIO FOREIGN KEY (cifcmatriz) REFERENCES CONCESIONARIOS(cifc)
);

CREATE TABLE DISTRIBUCION 
(cifc VARCHAR2(10),
codcoche NUMBER(5),
fecha DATE,

CONSTRAINT PK_DISTRIBUCION PRIMARY KEY (cifc,codcoche),
CONSTRAINT FK_DISTRIBUCION  FOREIGN KEY (cifc) REFERENCES CONCESIONARIOS(cifc),
CONSTRAINT FK2_DISTRIBUCION FOREIGN KEY (codcoche) REFERENCES COCHES(codcoche)
);

CREATE TABLE VENTAS
(codcoche NUMBER(5),
cifc VARCHAR2(10),
dni VARCHAR(9),
fechaventa DATE,
pvp NUMBER(5),

CONSTRAINT PK_VENTAS PRIMARY KEY (codcoche),
CONSTRAINT FK1_VENTAS FOREIGN KEY (cifc) REFERENCES CONCESIONARIOS(cifc),
CONSTRAINT FK2_VENTAS FOREIGN KEY (dni) REFERENCES CLIENTES(dni),
CONSTRAINT FK3_VENTAS FOREIGN KEY (codcoche) REFERENCES COCHES(codcoche)
);

ALTER TABLE VENTAS MODIFY (fechaventa DEFAULT SYSDATE);
ALTER TABLE COCHES ADD CONSTRAINT CHK1_COCHES CHECK (color IN('rojo','amarillo','verde') AND (color IN('ROJO','AMARILO','VERDE'))); 
ALTER TABLE CLIENTES ADD CONSTRAINT CHK1_CLIENTES CHECK (cuidad=UPPER(cuidad));
ALTER TABLE DISTRIBUCION ADD (area VARCHAR2(20));
ALTER TABLE DISTRIBUCION ADD CONSTRAINT CHK1_DISTRIBUCION CHECK (area LIKE '%T%');
ALTER TABLE CONCESIONARIOS DISABLE CONSTRAINT FK_CONCESIONARIO;
ALTER TABLE CONCESIONARIOS DROP CONSTRAINT FK_CONCESIONARIO;






