ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER INSERTAR IDENTIFIED BY INSERTAR;
GRANT CONNECT, RESOURCE, DBA TO INSERTAR; 

CREATE TABLE CABALLOS
(codcaballo VARCHAR2(4),
peso NUMBER(3) NOT NULL,
fecha_nacimiento DATE,
propietario VARCHAR2(25),
nacionalidad VARCHAR2(20),

CONSTRAINT PK_CABALLOS PRIMARY KEY (codcaballo),
CONSTRAINT CHK1_CABALLOS CHECK (peso BETWEEN 240 AND 300),
CONSTRAINT CHK2_CABALLOS CHECK (EXTRACT(YEAR FROM fecha_nacimiento)>2000),
CONSTRAINT CHK3_CABALLOS CHECK (nacionalidad= UPPER(nacionalidad))
);

CREATE TABLE CARRERAS
(codcarrera VARCHAR2(4),
fecha_hora DATE,
importe_premio NUMBER(6),
apuesta_limite NUMBER(5,2),

CONSTRAINT PK_CARRERAS PRIMARY KEY (codcarrera),
/*CONSTRAINT CHK1_CARRERAS CHECK (EXTRACT(MONTH FROM (fecha_hora NOT IN '3','8'))),*/
CONSTRAINT CHK2_CARRERAS CHECK (apuesta_limite<20000)
);

CREATE TABLE CLIENTES
(dni VARCHAR2(10),
nombre VARCHAR2(20),
nacionalidad VARCHAR2(20),

CONSTRAINT PK_CLIENTES PRIMARY KEY (dni),
CONSTRAINT CHK1_CLIENTES CHECK (regexp_like(dni,'[1-9]{8},[A-Z]{1},[%]{1}')),
CONSTRAINT CHK2_CLIENTES CHECK (nacionalidad=UPPER(nacionalidad))
);

CREATE TABLE APUESTAS 
(dni_cliente VARCHAR2(10),
codcaballo VARCHAR2(4),
codcarrera VARCHAR2(4),
importe NUMBER(6) DEFAULT 300 NOT NULL,
tantoporuno NUMBER(4,2),

CONSTRAINT PK_APUESTAS PRIMARY KEY (dni_cliente,codcaballo,codcarrera),
CONSTRAINT FK1_APUESTAS FOREIGN KEY (dni_cliente) REFERENCES CLIENTES(dni),
CONSTRAINT FK2_APUESTAS FOREIGN KEY (codcaballo) REFERENCES CABALLOS(codcaballo) ON DELETE CASCADE,
CONSTRAINT FK3_APUESRAS FOREIGN KEY (codcarrera) REFERENCES CARRERAS(codcarrera)
);

CREATE TABLE PARTICIPACIONES 
(codcaballo VARCHAR2(4),
codcarrera VARCHAR2(4),
dorsal NUMBER(2) NOT NULL,
jockey VARCHAR2(10) NOT NULL,
posicionfinal NUMBER(2),

CONSTRAINT PK_PARTICIPACIONES PRIMARY KEY (codcaballo,codcarrera),
CONSTRAINT FK1_PARTICIPACIONES FOREIGN KEY (codcaballo) REFERENCES CABALLOS(codcaballo),
CONSTRAINT FK2_PARTICIPACIONES FOREIGN KEY (codcarrera) REFERENCES CARRERAS(codcarrera),
CONSTRAINT CHK1_PARTICIPACIONES CHECK (posicionfinal>0)
);

ALTER TABLE PARTICIPACIONES ADD CONSTRAINT CHKMAYUS_PARTICIPACIONES CHECK (jockey = INITCAP(jockey));
/*ALTER TABLE CARRERAS ADD CONSTRAINT CHKFECHA_CARRERAS CHECK (fecha_hora(to_char('MM/DD')) BETWEEN '03/10' AND '10/10');*/
ALTER TABLE CABALLOS ADD CONSTRAINT CHKNACIONALIDAD_CABALLOS CHECK (nacionalidad IN ('Española','Britanica','Arabe'));
ALTER TABLE CABALLOS DROP (propietario);
ALTER TABLE CARRERAS ADD CONSTRAINT CHKIMPORTE_CARRERAS CHECK (importe_premio<=1000);
ALTER TABLE CLIENTES ADD (codigo VARCHAR2(5) UNIQUE);
ALTER TABLE APUESTAS ADD (premio NUMBER(4));
ALTER TABLE CARRERAS DISABLE CONSTRAINT CHKIMPORTE_CARRERAS;

/*DROP TABLE CABALLOS CASCADE CONSTRAINT;
DROP TABLE APUESTAS CASCADE CONSTRAINT;
DROP TABLE CARRERAS CASCADE CONSTRAINT;
DROP TABLE CLIENTES CASCADE CONSTRAINT;
DROP TABLE PARTICIPACIONES CASCADE CONSTRAINT;
*/


