CREATE TABLE FAMILIA
(nombre VARCHAR2(25),
caracteristicas VARCHAR2(100),

CONSTRAINT pk_familia PRIMARY KEY (nombre)
);

CREATE TABLE GENERO
(nombre VARCHAR2(25),
caracteristicas VARCHAR2(100),
nombre_familia VARCHAR2(25),

CONSTRAINT pk_GENERO PRIMARY KEY (nombre),
CONSTRAINT fk_GENERO FOREIGN KEY (nombre_familia) REFERENCES FAMILIA(nombre)
);

CREATE TABLE ESPECIE
(nombre VARCHAR2(25),
caracteristicas VARCHAR2(100),
nombre_genero VARCHAR2(25),

CONSTRAINT PK_ESPECIE PRIMARY KEY (nombre),
CONSTRAINT FK_ESPECIE FOREIGN KEY (nombre_genero) REFERENCES GENERO(nombre)
);

CREATE TABLE ZONA
(nombre VARCHAR2(25),
localidad VARCHAR(50),
extension NUMBER(25),
protegida VARCHAR2(20),

CONSTRAINT PK_ZONA PRIMARY KEY (nombre)
);

CREATE TABLE PERSONA
(dni NUMBER(9),
usuario VARCHAR2(25),
telefono NUMBER(9),
direccion VARCHAR2(30),
nombre VARCHAR2(25),

CONSTRAINT PK_PERSONA PRIMARY KEY (dni)
);

CREATE TABLE COLECCION
(dni NUMBER(9),
fecha_inicio DATE,
precio NUMBER(5),
n_ejemplares NUMBER(5),

CONSTRAINT PK_COLECCION PRIMARY KEY (dni),
CONSTRAINT FK_COLECCION FOREIGN KEY (dni) REFERENCES PERSONA(dni)
);

CREATE TABLE EJEMPLAR_MARIPOSA
(hora_captura NUMBER(2),
fecha_captura DATE,
dni_coleccion NUMBER(9),
nombre_especie VARCHAR2(25),
dni NUMBER(9),
nombre_zona VARCHAR2(25),
precio_ejemplar NUMBER(5),
nombre_comun VARCHAR2(25),
fecha_coleccion DATE,
CONSTRAINT PK_EJEMPLAR_MARIPOSA PRIMARY KEY (hora_captura, fecha_captura, dni_coleccion, nombre_especie, dni, nombre_zona),
CONSTRAINT FK1_EJEMPLAR_MARIPOSA FOREIGN KEY (dni_coleccion) REFERENCES COLECCION(dni),
CONSTRAINT FK2_EJEMPLAR_MARIPOSA FOREIGN KEY (dni) REFERENCES PERSONA(dni),
CONSTRAINT FK3_EJEMPLAR_MARIPOSA FOREIGN KEY (nombre_especie) REFERENCES ESPECIE(nombre),
CONSTRAINT FK4_EJEMPLAR_MARIPOSA FOREIGN KEY (nombre_zona) REFERENCES ZONA(nombre)
);

ALTER TABLE EJEMPLAR_MARIPOSA ADD CONSTRAINT chk1_EJEMPLAR_MARIPOSA CHECK (precio_ejemplar>0);
ALTER TABLE PERSONA MODIFY (usuario VARCHAR2(25) UNIQUE);
ALTER TABLE ZONA ADD CONSTRAINT chk1_zona CHECK (protegida IN ('SI','NO'));
ALTER TABLE COLECCION ADD CONSTRAINT chk2_zona CHECK (n_ejemplares BETWEEN 1 AND 150);
ALTER TABLE PERSONA ADD apellido VARCHAR2(50);
ALTER TABLE ZONA ADD CONSTRAINT chk3_zona CHECK (extension BETWEEN 100 AND 1500);
ALTER TABLE EJEMPLAR_MARIPOSA DISABLE CONSTRAINT chk1_EJEMPLAR_MARIPOSA;
CREATE INDEX indice_persona ON PERSONA(nombre);
CREATE INDEX indice_mariposa ON EJEMPLAR_MARIPOSA (fecha_captura);
