--ALTER SESSION SET "_oracle_script"=TRUE;
--CREATE USER TRIGGERS7V2 IDENTIFIED BY TRIGGERS7V2;
--GRANT CONNECT, RESOURCE, DBA TO TRIGGERS7V2;

CREATE TABLE empleados
(dni VARCHAR2(9) PRIMARY KEY,
nomemp VARCHAR2(50),
jefe VARCHAR2(9),
departamento NUMBER,
salario NUMBER(9,2) DEFAULT 1000,
usuario VARCHAR2(50),
fecha DATE,
CONSTRAINT FK_JEFE FOREIGN KEY (jefe) REFERENCES empleados (dni) );

--EJERCICIO1
CREATE OR REPLACE
TRIGGER JEFES
AFTER INSERT ON empleados
FOR EACH ROW
DECLARE 
NUM NUMBER:=0;
ERROR EXCEPTION;
BEGIN 
	IF INSERTING THEN
		SELECT COUNT(jefe) INTO NUM
		FROM EMPLEADOS 
		WHERE :NEW.DNI = :OLD.DNI;
		IF (NUM<5) THEN
			INSERT INTO empleados VALUES (:NEW.dni,:NEW.nomemp,:NEW.jefe,:NEW departamento,:NEW.salario,:NEW salario,:NEW usuario,:NEW.fecha);
		ELSE 
			RAISE ERROR;
		END IF;
	
	END IF;
EXCEPTION
WHEN ERROR THEN
	DBMS_OUTPUT.PUT_LINE('TIENE MAS DE 5 JEFES');
END JEFES;

INSERT INTO ('77889922L','JOSEJUAN','77889922L',20,2500,'CURRO',SYSDATE);

TRIGGER SALARIOS
BEFORE UPDATE OF salario ON empleados
FOR EACH ROW
DECLARE

BEGIN 
	IF (:NEW.salario>:OLD.salario*1.20) THEN
		RAISE_APPLICATION_ERROR('-20001','NO SE PUEDE ACTUALIZAR');
	END IF;
END SALARIOS;

UPDATE EMPLEADOS 
SET salario=salario*1.25
WHERE dni='99999922L';

UPDATE EMPLEADOS 
SET salario=salario*1.1
WHERE dni='99999922L';
